version: '3.8'

services:
 db:
   image: postgres
 web:
   container_name: spider_group_test_project
   build: .
   command: bash -c "python /code/manage.py migrate --noinput && gunicorn -c gunicorn.conf.py spider_group_test_project.wsgi"
   volumes:
     - .:/code
   env_file:
     - .environment
   ports:
     - "8000:8000"
   depends_on:
     - db
